plugins { id 'com.android.application' }

android {
    namespace 'com.reviewbetterbonia.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.reviewbetterbonia.app'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '3.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes { release { minifyEnabled false } }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:33.7.0')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'androidx.fragment:fragment:1.8.9'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
}
